---
- hosts: all
  remote_user: root
  tasks:
  - name: Ensure that Samba package is installed
    apt:
      name: samba
      state: present
  - name: Ensure the Samba service is enabled and running
    service:
      name: smbd
      state: started
      enabled: True
    become: True
  - name: create shared folder
    file:
      path: /share
      state: directory
  - name: create group
    group:
      name: sambausers
      state: present
  - name: change ownership
    file:
      path: /share
      owner: root
      group: sambausers
      mode: 0770
  - name: writing example smb share
    blockinfile:
      dest: /etc/samba/smb.conf
      block: |
        [sambashare]
            comment = Samba
            path = /share
            writeable = yes
            browsable = yes
            valid users = @sambausers
      backup: yes
