---
- hosts: all
  remote_user: root
  tasks:
  - name: Ensure the apache2 package is installed
    apt:
      name: apache2
      state: present
      become: True
  - name: Ensure the apache2 service is enabled and running
    service:
      name: apache2
      state: started
      enabled: True
    become: True
