---
- hosts: all
  remote_user: root
  tasks:
  - name: Ensure that Samba package is installed
    apt:
      name: samba
      state: present
  - name: Ensure the Samba service is enabled and running
    service:
      name: smbd
      state: started
      enabled: True
    become: True
  - lineinfile:
      path: /etc/samba/smb.conf
      line: '192.168.1.99 foo.lab.net foo'
