---
- hosts: all
  remote_user: root
  tasks:
  - name: Ensure that Samba package is installed
    apt:
      name: samba
      state: present
  - name: Ensure the Samba service is enabled and running
    service:
      name: samba
      state: started
      enabled: True
    become: True
